INSERT INTO ecs_input_type (id, input_type) VALUES (1, 'text');
INSERT INTO ecs_input_type (id, input_type) VALUES (2, 'date');
INSERT INTO ecs_input_type (id, input_type) VALUES (3, 'yn');
INSERT INTO ecs_input_type (id, input_type) VALUES (4, 'select');
INSERT INTO ecs_input_type (id, input_type) VALUES (5, 'checkbox');
INSERT INTO ecs_input_type (id, input_type) VALUES (6, 'radiobox');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (1, 1,'Beneficiary’s name (First, Middle, Last)');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (2, 1,'Medicare number');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (3, 1,'Item or service you wish to appeal');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (4, 2,'Date the service or item was received (mm/dd/yyyy');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (5, 2,'Date of the initial determination notice (mm/dd/yyyy) (please include a copy of the notice with this request)');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (6, 1,'If you received your initial determination notice more than 120 days ago, include your reason for the late filing:');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (7, 1,'Name of the Medicare contractor that made the determination (not required) ');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (8, 3,'Does this appeal involve an overpayment? (for providers and suppliers only) ');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (9, 1,'I do not agree with the determination decision on my claim because: ');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (10, 1,'Additional information Medicare should consider:');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (11, 5,'I have evidence to submit.');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (12, 5,'I do not have evidence to submit.');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (13, 5,'Person appealing:');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (14, 1,'Email of person appealing (optional)');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (15, 1,'Name of person appealing (First, Middle, Last)');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (16, 1,'Street address of person appealing ');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (17, 1,'City');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (18, 1,'State');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (19, 1,'Zip code');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (20, 1,'Telephone number of person appealing (include area code)');
INSERT INTO ecs_question (id, question_input_type, question_name) VALUES (21, 1,'Date of appeal (mm/dd/yyyy) (optional)');
COMMIT;
