CREATE ROLE :dbAppRole
    WITH NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE :dbAppUser
    WITH LOGIN PASSWORD ':dbAppUserPassword'
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION IN ROLE :dbAppRole;

GRANT ALL ON DATABASE :dbName TO :dbAdmin;
GRANT CONNECT, TEMPORARY ON DATABASE :dbName TO :dbAppRole;
REVOKE ALL ON DATABASE :dbName FROM public;

CREATE SCHEMA :dbSchema AUTHORIZATION :dbAdmin;
GRANT USAGE ON SCHEMA :dbSchema TO :dbAppRole;

ALTER DEFAULT PRIVILEGES IN SCHEMA :dbSchema
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO :dbAppRole;

ALTER DEFAULT PRIVILEGES IN SCHEMA :dbSchema
    GRANT SELECT, USAGE ON SEQUENCES TO :dbAppRole;

CREATE SCHEMA IF NOT EXISTS :liquibaseSchema AUTHORIZATION :dbAdmin;